name: Tests

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1

      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install tox

      - name: Run tests
        run: tox
